# Generated by Django 4.0 on 2021-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_categories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='courses.Categories')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
