# Generated by Django 4.0 on 2022-02-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'permissions': [('premium_user', 'Can access all lessons')], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lessons'),
        ),
    ]
