# Generated by Django 4.0 on 2022-02-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
    ]
