version: "3.3"
services: 
  postgres: 
    image: postgres:12.8
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lms
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432