---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true
      notify:
        - Start Nginx

# working with handlers, their job is to listen for an event and then run when event is triggered
  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started